[package]
name = "wasm_udf"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]

arrow = {  workspace = true }
paste = { version = "1.0" }
wasmedge-bindgen = { version = "0.4.1"}
wasmedge-bindgen-macro = { version = "0.4.1" }
